org: rimironenko
app: aws-serverless-framework-app
service: items-api

frameworkVersion: '2'

provider:
  name: aws
  runtime: java8
  lambdaHashingVersion: 20201221
  environment:
    TABLE: ${self:service}-${sls:stage}-BooksDynamoDbTable-${sls:instanceId}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:BatchGetItem
      Resource: "arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${self:provider.environment.TABLE}"

package:
  artifact: target/aws-serverless-framework-app-dev.jar

functions:
  getItem:
    handler: com.home.amazon.serverless.lambda.GetItemFunction
    events:
      - http:
          path: /books/{isbn}
          method: get

resources:
  Resources:
    BooksDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          - AttributeName: isbn
            AttributeType: S
        KeySchema:
          - AttributeName: isbn
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        SSESpecification:
          SSEEnabled: true
        TableName: ${self:provider.environment.TABLE}